services:
  worker:
    image: ${COMPOSE_PROJECT_NAME}/worker:${VERSION:-0.1.0}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-worker
    hostname: worker
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      CAASM_LOGGER_FORMATTER: ${LOGGER_FORMATTER:-%(asctime)s %(levelprefix)s %(message)s}
