services:
  web-dev:
    extends:
      file: ./base.yml
      service: web
    container_name: ${COMPOSE_PROJECT_NAME}-web-dev
    volumes:
      - .:/usr/src/app
    profiles:
      - dev
    ports:
      - 8000:8000