services:
  web-dev:
    extends:
      file: ./base.yml
      service: web
    container_name: ${COMPOSE_PROJECT_NAME}-web-dev
    volumes:
      - .:/app
      - ../shared:/app/shared
      - /app/.venv
    profiles:
      - dev
    ports:
      - 8000:8000